apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: express-deployment-k8s
  namespace: backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app-k8s-container
        image: dipakkhade/express-app-kubernetes
        ports: 
          - containerPort: 3000

